/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswingdev.form;

import DAO.ChatLieuDAO;
import DAO.ChiTietSanPhamDAO;
import DAO.ColorDAO;
import DAO.LoaiSPDAO;
import DAO.ProductsDAO;
import DAO.SizeDAO;
import DomainModel.ChatLieu;
import DomainModel.ChiTietSanPham;
import DomainModel.Color;
import DomainModel.LoaiSP;
import DomainModel.Products;
import DomainModel.Size;
import Validate.Validation;
import Validate.Validation1;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhapHangForm extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    DefaultTableModel df = new DefaultTableModel();
    int index;
    int indexx;
    List<ChiTietSanPham> listPro = new ArrayList<>();
    List<ChiTietSanPham> listNhapHang = new ArrayList<>();
    ChiTietSanPhamDAO proDAO = new ChiTietSanPhamDAO();
    ColorDAO mauDAO = new ColorDAO();
    SizeDAO sizeDAO = new SizeDAO();
    ChatLieuDAO clieuDao = new ChatLieuDAO();
    LoaiSPDAO loaiSpDAO = new LoaiSPDAO();
    ProductsDAO spDAO = new ProductsDAO();

    /**
     * Creates new form NhapHang
     */
    public NhapHangForm() {
        listPro = proDAO.selectAll();
        initComponents();
        defaultTableModel = (DefaultTableModel) tblSanPham.getModel();
        df = (DefaultTableModel) tblNhapHang.getModel();
        rdoAll.setSelected(true);
        show3(0);
        fillComboboxProduct();

    }

    public void tblNhap(ChiTietSanPham x) {
        DefaultTableModel df = new DefaultTableModel();

        List<ChiTietSanPham> newList;
        /*List<ChiTietSanPham> list = proDAO.selectAll();
        
        df.setRowCount(0);
        
        df.addRow(new Object[]{ x.getIdCTSP(),  x.getLoaiSp(),  x.getTenSp(), 
             x.getMau(),x.getKichThuoc(),  x.getChatLieu(), x.getSoLuong(),  x.getGia()});
        
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentResizer1 = new javaswingdev.swing.titlebar.ComponentResizer();
        roundPanel1 = new javaswingdev.swing.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbbLoaiSp2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbbMau2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbbChatLieu2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rdoduoi = new javax.swing.JRadioButton();
        rdotren = new javax.swing.JRadioButton();
        txtMucDinhTon = new javax.swing.JTextField();
        rdoAll = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSetSL = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdSp = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhapHang = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("NHẬP HÀNG");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Tìm");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cbbLoaiSp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbLoaiSp2.setBorder(null);
        cbbLoaiSp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiSp2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Loại Sp");

        cbbMau2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMau2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Màu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Chất Liệu");

        cbbChatLieu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbChatLieu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChatLieu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbLoaiSp2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbMau2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbbChatLieu2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbLoaiSp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbMau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbChatLieu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Giá Bán");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton1.setText("Từ thấp đến cao");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Từ cao đến thấp");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rdoduoi.setText("Dưới mức định tồn");
        rdoduoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoduoiActionPerformed(evt);
            }
        });

        rdotren.setText("Vượt mức định tồn");
        rdotren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdotrenActionPerformed(evt);
            }
        });

        txtMucDinhTon.setText("10");
        txtMucDinhTon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMucDinhTonKeyTyped(evt);
            }
        });

        rdoAll.setSelected(true);
        rdoAll.setText("Tất cả");
        rdoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAllActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tồn kho");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Mức định tồn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(rdoAll)
                    .addComponent(rdotren)
                    .addComponent(rdoduoi)
                    .addComponent(txtMucDinhTon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMucDinhTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdoduoi)
                .addGap(18, 18, 18)
                .addComponent(rdotren)
                .addContainerGap())
        );

        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTable.setBackground(new java.awt.Color(223, 207, 190));
        panelTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Sp", "Loại Sp", "Tên Sp", "Màu", "Kích Thước", "Chất Liệu", "Số Lượng", "Giá Bán"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng");

        txtSetSL.setBackground(new java.awt.Color(223, 207, 190));
        txtSetSL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSetSL.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Lưu tạm");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Id sp");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Xóa tạm");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Xóa Tất Cả");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTableLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jSeparator4))
                            .addGroup(panelTableLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdSp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTableLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSetSL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(panelTableLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdSp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtSetSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tblNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Sp", "Loại Sp", "Tên Sp", "Màu", "Kích Thước", "Chất Liệu", "Số Lượng", "Giá "
            }
        ));
        tblNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhapHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhapHang);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setText("Tạo Hóa Đơn");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nhập Hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thông Tin Sản Phẩm");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtSearch))
                        .addGap(64, 64, 64)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(250, 250, 250))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(495, 495, 495)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        rdoAll.setSelected(true);
        try {
            searchTable();
        } catch (Exception e) {
            searchKeyFillTable();

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cbbLoaiSp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiSp2ActionPerformed
        boLoc();
    }//GEN-LAST:event_cbbLoaiSp2ActionPerformed

    private void cbbMau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMau2ActionPerformed
        boLoc();
    }//GEN-LAST:event_cbbMau2ActionPerformed

    private void cbbChatLieu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChatLieu2ActionPerformed
        boLoc();
    }//GEN-LAST:event_cbbChatLieu2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        listPro = boLoc();
        Collections.sort(listPro, (a, b) -> (int) (a.getGia() - b.getGia()));
        defaultTableModel.setRowCount(0);

        for (ChiTietSanPham x : listPro) {
            defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        listPro = boLoc();
        Collections.sort(listPro, (a, b) -> (int) (b.getGia() - a.getGia()));
        defaultTableModel.setRowCount(0);

        for (ChiTietSanPham x : listPro) {
            defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rdoduoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoduoiActionPerformed
        duoiMuc();
    }//GEN-LAST:event_rdoduoiActionPerformed

    private void rdotrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdotrenActionPerformed
        trenMuc();
    }//GEN-LAST:event_rdotrenActionPerformed

    private void txtMucDinhTonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMucDinhTonKeyTyped
        if (rdoduoi.isSelected()) {
            duoiMuc();
        }
        if (rdotren.isSelected()) {
            trenMuc();
        }
    }//GEN-LAST:event_txtMucDinhTonKeyTyped

    private void rdoAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAllActionPerformed
        fillToTable();
        cbbChatLieu2.setSelectedIndex(0);
        cbbMau2.setSelectedIndex(0);
        cbbLoaiSp2.setSelectedIndex(0);
    }//GEN-LAST:event_rdoAllActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        index = tblSanPham.getSelectedRow();
        show3(index);
        tblNhap(listPro.get(index));
        txtIdSp.setText(tblSanPham.getValueAt(index, 0).toString());
        /* System.out.println("-------------------------------------------");
        System.out.println(tblSanPham.getValueAt(index, 0).toString());
        System.out.println(tblSanPham.getValueAt(index, 1).toString());
        System.out.println(tblSanPham.getValueAt(index, 2).toString());
        System.out.println(tblSanPham.getValueAt(index, 3).toString());
        System.out.println(tblSanPham.getValueAt(index, 4).toString());
        System.out.println(tblSanPham.getValueAt(index, 5).toString());
        System.out.println(tblSanPham.getValueAt(index, 6).toString());
        System.out.println(tblSanPham.getValueAt(index, 7).toString());
        System.out.println("-------------------------------------------"); */

    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void tblNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhapHangMouseClicked

    }//GEN-LAST:event_tblNhapHangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        luuTam();
        df.setRowCount(0);
        for (ChiTietSanPham x : listNhapHang) {
            df.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(),
                x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        removeSP();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        removeAllSp();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        taoHoaDon();
    }//GEN-LAST:event_jButton7ActionPerformed
    private boolean removeSP() {
        int i = tblNhapHang.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Chọn sp muốn xóa", "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (Question("Bạn có muốn xóa sp")) {
            return true;
        }
        listNhapHang.remove(i);
        df.setRowCount(0);
        for (ChiTietSanPham x : listNhapHang) {
            df.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(),
                x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
        return false;
    }

    private boolean removeAllSp() {
        if (Question("Bạn có muốn xóa tất cả sp")) {
            return true;
        }
        listNhapHang.clear();
        df.setRowCount(0);

        return false;
    }

    private boolean taoHoaDon() {
        int m,n;
        if (listNhapHang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng trống! Vui lòng chọn thêm sp");
            return true;
        }
        if (Question("Tạo hóa đơn?")) {
            return true;
        }
        for (ChiTietSanPham k : listNhapHang) {
            for (ChiTietSanPham h : listPro) {
                if (h.getIdCTSP() == k.getIdCTSP()) {
                    m = h.getSoLuong() + k.getSoLuong();
                    k.setSoLuong(m);
                    proDAO.updateSl(k);
                }

            }

        }
        //;
        listNhapHang.clear();
        df.setRowCount(0);
        boLoc();
        index = -1;
        txtSetSL.setText("");
        txtIdSp.setText("");
//txtIdSp.setText(String.valueOf(listPro.get(0).getIdCTSP()));

        return false;
    }

    private boolean luuTam() {
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Chọn sp muốn thêm", "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (Validation1.iEmpty(txtSetSL, "Số lượng không đươc để trống")) {
            return true;
        }
        if (Validation1.isNotInt(txtSetSL, "Nhâp số lượng là nguyên dương")) {
            return true;
        }
        txtSetSL.setBackground(new java.awt.Color(223,207,190));
        if (Question("Thêm sp vào hóa đơn?")) {
            return true;
        }

        ChiTietSanPham x = new ChiTietSanPham();
        // x.getIdCTSP(),  x.getLoaiSp(),  x.getTenSp(), 
        //    x.getMau(),x.getKichThuoc(),  x.getChatLieu(), x.getSoLuong(),  x.getGia()});
        int id, soLuong;
        float giaBan, gia;
        String ten, mau, loai, chatLieu, kichThuoc;

        try {
            String idS = tblSanPham.getValueAt(index, 0).toString();
            id = Integer.parseInt(idS);
            loai = tblSanPham.getValueAt(index, 1).toString();
            ten = tblSanPham.getValueAt(index, 2).toString();
            mau = tblSanPham.getValueAt(index, 3).toString();
            kichThuoc = tblSanPham.getValueAt(index, 4).toString();
            chatLieu = tblSanPham.getValueAt(index, 5).toString();
            soLuong = Integer.parseInt(txtSetSL.getText());
            giaBan = Float.parseFloat(tblSanPham.getValueAt(index, 7).toString());
            gia = (float) (giaBan * 0.8);
            x.setIdCTSP(id);
            x.setTenSp(ten);
            x.setChatLieu(chatLieu);
            x.setLoaiSp(loai);
            x.setGia(gia);
            x.setSoLuong(soLuong);
            x.setMau(mau);
            x.setKichThuoc(kichThuoc);
            boolean check = false;
            for (ChiTietSanPham j : listNhapHang) {
                if (j.getIdCTSP() == id) {
                    soLuong = soLuong + j.getSoLuong();
                    listNhapHang.remove(j);
                    listNhapHang.add(x);
                    check = true;
                    break;
                }
            }
            if (check == false) {
                listNhapHang.add(x);
            }
        } catch (IndexOutOfBoundsException numberFormatException) {
            System.out.println("1");
        }

        return false;
    }

    private boolean Question(String mess) {
        int choice = JOptionPane.showConfirmDialog(this, mess, "Question", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION || choice == JOptionPane.CLOSED_OPTION) {
            return true;
        }
        return false;
    }

    public void fillToTable() {

        defaultTableModel.setRowCount(0);
        List<ChiTietSanPham> listPro = proDAO.selectAll();
        for (ChiTietSanPham x : listPro) {
            defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }

    }

    public void fillComboboxProduct() {

        DefaultComboBoxModel cbMau2 = (DefaultComboBoxModel) cbbMau2.getModel();

        DefaultComboBoxModel cbLoai2 = (DefaultComboBoxModel) cbbLoaiSp2.getModel();

        DefaultComboBoxModel cbChat2 = (DefaultComboBoxModel) cbbChatLieu2.getModel();

        cbbMau2.removeAllItems();

        cbbChatLieu2.removeAllItems();

        cbbLoaiSp2.removeAllItems();

        cbMau2.addElement("All");
        cbChat2.addElement("All");
        cbLoai2.addElement("All");
        List<Color> listColor = new ArrayList<>();
        listColor = mauDAO.selectAll();
        for (Color p : listColor) {
            String x = p.getTenMau();

            cbMau2.addElement(x);
        }
        List<ChatLieu> listCL = new ArrayList<>();
        listCL = clieuDao.selectAll();
        for (ChatLieu p : listCL) {
            String x = p.getTenChatLieu();

            cbChat2.addElement(x);
        }

        List<LoaiSP> listLoaiSp = new ArrayList<>();
        listLoaiSp = loaiSpDAO.selectAll();
        for (LoaiSP p : listLoaiSp) {
            String x = p.getTenLoaiSP();

            cbLoai2.addElement(x);
        }

    }

    private int muc() {
        int i = 10;
        try {
            i = Integer.parseInt(txtMucDinhTon.getText());
        } catch (Exception e) {
        }
        return i;
    }

    private void duoiMuc() {
        listPro = proDAO.selectAll();
        List<ChiTietSanPham> newList = new ArrayList<>();
        for (ChiTietSanPham x : listPro) {
            if (x.getSoLuong() <= muc()) {
                newList.add(x);
            }
        }
        defaultTableModel.setRowCount(0);

        for (ChiTietSanPham x : newList) {
            defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
    }

    private void trenMuc() {
        listPro = proDAO.selectAll();
        List<ChiTietSanPham> newList = new ArrayList<>();
        for (ChiTietSanPham x : listPro) {
            if (x.getSoLuong() > muc()) {
                newList.add(x);
            }
        }
        defaultTableModel.setRowCount(0);

        for (ChiTietSanPham x : newList) {
            defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
        }
    }

    public ChiTietSanPham searchTable() {
        // tìm kiếm theo mã sản phẩm
        defaultTableModel = (DefaultTableModel) tblSanPham.getModel();
        defaultTableModel.setRowCount(0);
        int keyWord = Integer.parseInt(txtSearch.getText());

        ChiTietSanPham x = proDAO.selectById(keyWord);

        defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(), x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});

        return x;
    }

    public List<ChiTietSanPham> searchKeyFillTable() {
        // tìm kiếm theo tên sản phẩm
        String key = txtSearch.getText();
        defaultTableModel = (DefaultTableModel) tblSanPham.getModel();
        defaultTableModel.setRowCount(0);
        List<ChiTietSanPham> list = proDAO.selectByKey(key);
        List<ChiTietSanPham> lists = boLoc();
        List<ChiTietSanPham> listss = new ArrayList<>();
        defaultTableModel.setRowCount(0);
        for (ChiTietSanPham x : list) {
            for (ChiTietSanPham i : lists) {
                if (i.getIdCTSP() == x.getIdCTSP()) {
                    defaultTableModel.addRow(new Object[]{x.getIdCTSP(), x.getLoaiSp(), x.getTenSp(), x.getMau(),
                        x.getKichThuoc(), x.getChatLieu(), x.getSoLuong(), x.getGia()});
                    listss.add(i);
                }
            }
        }
        defaultTableModel.fireTableDataChanged();
        return listss;
    }

    private List<ChiTietSanPham> boLoc1() {
        listPro = proDAO.selectAll();
        List<ChiTietSanPham> newList = new ArrayList<>();

        String loai = "All";
        String mau = "All";
        String chatLieu = "All";

        try {
            loai = cbbLoaiSp2.getSelectedItem().toString();
            mau = cbbMau2.getSelectedItem().toString();
            chatLieu = cbbChatLieu2.getSelectedItem().toString();
        } catch (Exception e) {
        }

        for (ChiTietSanPham x : listPro) {
            if (loai.equalsIgnoreCase("All") && mau.equalsIgnoreCase("All") && chatLieu.equalsIgnoreCase("All")) {
                newList = listPro;
            }

            if (loai.equalsIgnoreCase("All")) {
                if (mau.equalsIgnoreCase("All")) {
                    if (chatLieu.equalsIgnoreCase(x.getChatLieu())) {
                        newList.add(x);
                    }
                } else {
                    if (chatLieu.equalsIgnoreCase("All")) {
                        if (mau.equalsIgnoreCase(x.getMau())) {
                            newList.add(x);
                        }
                    } else {
                        if (mau.equalsIgnoreCase(x.getMau()) && chatLieu.equalsIgnoreCase(x.getChatLieu())) {
                            newList.add(x);
                        }
                    }
                }
            }
            if (loai.equalsIgnoreCase(x.getLoaiSp())) {
                if (mau.equalsIgnoreCase("All") && chatLieu.equalsIgnoreCase("All")) {
                    newList.add(x);
                } else if (mau.equalsIgnoreCase("All") && chatLieu.equalsIgnoreCase(x.getChatLieu())) {
                    if (chatLieu.equalsIgnoreCase(x.getChatLieu())) {
                        newList.add(x);
                    }
                } else if (mau.equalsIgnoreCase(x.getMau()) && chatLieu.equalsIgnoreCase("All")) {
                    if (mau.equalsIgnoreCase(x.getMau())) {
                        newList.add(x);
                    }
                } else {
                    if (mau.equalsIgnoreCase(x.getMau()) && chatLieu.equalsIgnoreCase(x.getChatLieu())) {
                        newList.add(x);
                    }
                }
            }
        }

        return newList;
    }

    private List<ChiTietSanPham> boLoc() {
        List<ChiTietSanPham> newList = boLoc1();
        defaultTableModel.setRowCount(0);
        for (ChiTietSanPham i : newList) {
            defaultTableModel.addRow(new Object[]{i.getIdCTSP(), i.getLoaiSp(), i.getTenSp(), i.getMau(),
                i.getKichThuoc(), i.getChatLieu(), i.getSoLuong(), i.getGia()});
        }
        return newList;
    }

    private void show(int i) {
        listPro = boLoc1();

    }

    private void show3(int i) {
        List<ChiTietSanPham> listPros = new ArrayList<>();
        ChiTietSanPham x = new ChiTietSanPham();
        try {
            x = searchTable();
        } catch (Exception e) {
            listPros = searchKeyFillTable();
        }
        if (listPros.isEmpty()) {
            listPros = boLoc1();
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbChatLieu2;
    private javax.swing.JComboBox<String> cbbLoaiSp2;
    private javax.swing.JComboBox<String> cbbMau2;
    private javaswingdev.swing.titlebar.ComponentResizer componentResizer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panelTable;
    private javax.swing.JRadioButton rdoAll;
    private javax.swing.JRadioButton rdoduoi;
    private javax.swing.JRadioButton rdotren;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javax.swing.JTable tblNhapHang;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel txtIdSp;
    private javax.swing.JTextField txtMucDinhTon;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSetSL;
    // End of variables declaration//GEN-END:variables
}
